#!/usr/bin/env python3
"""Download placeholder imagery and self-hosted fonts.

This site is deliberately light on photography. The open-licence pool for
modern heat-treatment shops is poor — mostly archival scans — and mediocre
stock would undercut the whole pitch. So the visual language is generative
(heat gradients, real tempering-colour science, technical diagrams) and
photography is used only where it genuinely earns its place: colour
metallography plates, furnace interiors, hardness testing.

Everything here is a PLACEHOLDER. None of it shows Everest's own plant.
See CREDITS.md, regenerated by this script.

    python3 fetch_media.py            # skips what exists
    python3 fetch_media.py --force
"""
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
IMG_DIR = os.path.join(ROOT, "build_src", "img")
FONT_DIR = os.path.join(ROOT, "fonts")
DATA_DIR = os.path.join(ROOT, "src_data")

UA = "EverestHeatTreatersConcept/1.0 (https://github.com/hari-learns; placeholder media)"
COMMONS_API = "https://commons.wikimedia.org/w/api.php"
THUMB_WIDTH = 2400
FORCE = "--force" in sys.argv

MEDIA = {
    # --- microstructure: the visual signature of the trade ---------------
    "micro-colour":     "Color Metallography of Engineering Alloys.jpg",
    "micro-stainless":  "Microstructure of a stainless steel.jpg",
    "micro-stainless2": "Microstructure of a stainless steel A961.jpg",
    "micro-duplex":     "Duplex stainlss steel microstructure of heat affected zone.jpg",
    "micro-ferrite":    "Ferrite-perlite-steel-A285.jpeg",
    "micro-duplex4":    "Microstructures of four kinds of duplex stainless steel in each direction.jpg",

    # --- furnace + process ----------------------------------------------
    "furnace-castings": "Castings fresh from the heat treatment furnace.jpg",
    "furnace-computer": "Computerised Heat Treatment Furnance.jpg",
    "furnace-metal":    "Metallurgical Furnace in Guwahati, Assam.jpg",
    "furnace-anneal":   "Annealing furnace Saltford Brass Mill.jpg",
    "furnace-vacuum":   "Operating a vacuum heat treating furnace, by the Watertown Arsenal, United States Army, c. 1959–1962, from the Digital Commonwealth - commonwealth 2n49vs61t.jpg",

    # --- molten / glowing ------------------------------------------------
    "molten-pour":      "In-stream inoculation addition while molten cast iron is poured to a green sand mold in a foundry in Bangladesh.jpg",
    "molten-ladle":     "Dalsbruk - Gjutskänkar.jpg",
    "forge":            "Forja artesanal. Yunque y fragua. Taller de Sergi Cadenas, en Gerona o Girona. Cataluña, España.jpg",

    # --- testing + parts --------------------------------------------------
    "hardness-tester":  "Rockwell hardness tester 001.jpg",
    "hardness-close":   "Rockwell hardness tester closeup 001.jpg",
    "forged-part":      "VK Huette Schmiedeprodukt.JPG",
    "crankshaft":       "Klika - postup.jpg",
}

FONTS_CSS = ("https://fonts.googleapis.com/css2"
             "?family=Archivo:wght@400..700"
             "&family=JetBrains+Mono:wght@400;500&display=swap")


def get(url, headers=None, timeout=90):
    h = {"User-Agent": UA}
    h.update(headers or {})
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=h), timeout=timeout).read()


def strip_html(s):
    return re.sub(r"\s+", " ", re.sub("<[^>]+>", " ", s or "")).strip()


def decodes(path):
    """Pillow must fully decode it. Image.open() alone accepts a truncated
    download; load() is what forces the pixels through."""
    try:
        from PIL import Image
    except ImportError:
        return True
    try:
        with Image.open(path) as im:
            im.load()
        return True
    except Exception:
        return False


def commons_lookup(titles):
    out = {}
    for i in range(0, len(titles), 20):
        chunk = titles[i:i + 20]
        url = COMMONS_API + "?" + urllib.parse.urlencode({
            "action": "query", "format": "json",
            "titles": "|".join("File:" + t for t in chunk),
            "prop": "imageinfo", "iiprop": "url|size|extmetadata",
            "iiurlwidth": str(THUMB_WIDTH),
        })
        data = json.loads(get(url))
        for page in ((data.get("query") or {}).get("pages") or {}).values():
            info = (page.get("imageinfo") or [None])[0]
            if not info:
                print(f"  !! not found: {page.get('title')}")
                continue
            meta = info.get("extmetadata", {})
            out[page["title"][5:]] = {
                "url": info.get("thumburl") or info["url"],
                "descriptionurl": info.get("descriptionurl", ""),
                "artist": strip_html(meta.get("Artist", {}).get("value", "")) or "Unknown",
                "license": strip_html(meta.get("LicenseShortName", {}).get("value", "")) or "see source",
                "license_url": meta.get("LicenseUrl", {}).get("value", ""),
            }
        time.sleep(0.3)
    return out


def fetch_images():
    os.makedirs(IMG_DIR, exist_ok=True)
    os.makedirs(DATA_DIR, exist_ok=True)
    print(f"==> resolving {len(MEDIA)} files on Wikimedia Commons")
    resolved = commons_lookup(sorted(set(MEDIA.values())))

    credits, got, skipped, failed = {}, 0, 0, []
    for slug, title in MEDIA.items():
        info = resolved.get(title)
        if not info:
            failed.append(slug)
            continue
        credits[slug] = {"title": title,
                         **{k: v for k, v in info.items() if k != "url"}}

        dest = os.path.join(IMG_DIR, slug + ".jpg")
        if os.path.exists(dest) and not FORCE and decodes(dest):
            skipped += 1
            continue

        for attempt in (1, 2, 3):
            try:
                blob = get(info["url"])
                if len(blob) < 5000 or blob[:2] != b"\xff\xd8":
                    raise ValueError(f"not a JPEG ({len(blob)} bytes)")
                with open(dest, "wb") as fh:
                    fh.write(blob)
                if not decodes(dest):
                    raise ValueError("truncated — does not decode")
                print(f"  {slug:<18} {len(blob) // 1024:>5} KB")
                got += 1
                time.sleep(0.2)
                break
            except Exception as exc:
                if attempt == 3:
                    print(f"  !! {slug}: {exc}")
                    if os.path.exists(dest):
                        os.remove(dest)
                    failed.append(slug)
                else:
                    time.sleep(1.5 * attempt)

    with open(os.path.join(DATA_DIR, "credits.json"), "w") as fh:
        json.dump(credits, fh, indent=2, sort_keys=True)
    write_credits_md(credits)
    print(f"\n  downloaded {got}, already had {skipped}, failed {len(failed)}")
    if failed:
        print(f"  missing: {', '.join(failed)}")
        print("  (the build falls back to a heat-gradient block — it will not crash)")


def write_credits_md(credits):
    lines = [
        "# Image credits",
        "",
        "**Every image on this concept is a placeholder.** None of it shows",
        "Everest Heat Treaters' own plant, equipment or work. All of it is",
        "replaced with the company's own photography before launch.",
        "",
        "Sourced from Wikimedia Commons under the licences below.",
        "Regenerated by `fetch_media.py` — do not edit by hand.",
        "",
        "| File | Source | Author | Licence |",
        "|---|---|---|---|",
    ]
    for slug in sorted(credits):
        c = credits[slug]
        author = c["artist"].replace("|", "/")[:70]
        lic = f"[{c['license']}]({c['license_url']})" if c["license_url"] else c["license"]
        lines.append(f"| `{slug}` | [{c['title'][:50]}]({c['descriptionurl']}) | {author} | {lic} |")
    lines.append("")
    with open(os.path.join(ROOT, "CREDITS.md"), "w") as fh:
        fh.write("\n".join(lines))


def fetch_fonts():
    os.makedirs(FONT_DIR, exist_ok=True)
    print("\n==> fonts")
    chrome = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
              "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")
    css = get(FONTS_CSS, headers={"User-Agent": chrome}).decode()
    wanted = {}
    for subset, block in re.findall(
            r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css):
        if subset != "latin":
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block)
        src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if fam and src:
            wanted[fam.group(1).lower().replace(" ", "-")] = src.group(1)
    if not wanted:
        print("  !! no latin woff2 found — falling back to system fonts")
        return
    for name, url in wanted.items():
        dest = os.path.join(FONT_DIR, name + ".woff2")
        if os.path.exists(dest) and not FORCE:
            print(f"  {name:<18} (have)")
            continue
        try:
            blob = get(url, headers={"User-Agent": chrome})
            with open(dest, "wb") as fh:
                fh.write(blob)
            print(f"  {name:<18} {len(blob) // 1024:>5} KB")
        except Exception as exc:
            print(f"  !! {name}: {exc}")


if __name__ == "__main__":
    fetch_images()
    fetch_fonts()
    print("\nnext: python3 assets.py")
